main: com.gmail.xtendspb.plugins.bedspawnprotection.BedSpawnProtection
name: BedSpawnProtection
version: 1.1DinnerEdition
authors: [XtenD, Dinnerspond_]
description: Protects Players From Bed Killers
